services:
  airypay.discord:
    image: airypay.discord:latest
    environment:
      - "DISCORD_TOKEN=${DISCORD_TOKEN}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_PORT=5432"
    build:
      context: .
      dockerfile: src/AiryPayNew.Discord/Dockerfile
    volumes:
      - ./src:/app/src
      - ./appsettings.json:/app/appsettings.json:ro
      - ./paymentsettings.yaml:/app/paymentsettings.yaml:ro
    depends_on:
      - postgres
    restart: always
  
  airypay.web:
    image: airypay.web:latest
    environment:
      - "DISCORD_TOKEN=${DISCORD_TOKEN}"
    build:
      context: .
      dockerfile: src/AiryPayNew.Web/Dockerfile
    volumes:
      - ./src:/app/src
      - ./appsettings.json:/app/appsettings.json:ro
      - ./paymentsettings.yaml:/app/paymentsettings.yaml:ro
    depends_on:
      - postgres
    ports:
      - "80:80"
    restart: always  
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_OUTER_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
