# Positive decimal numbers 
defaultShopCommission: 10.0

ruKassaSettings:
  merchantId: 0
  token: ""
  userEmail: ""
  userPassword: ""

finPaySettings:
  shopId: 1
  key1: ""
  key2: ""

payPalSettings:
  "clientId": 0
  "secret": ""
  "sandbox": true

stripeSettings:
  "apiKey": ""
  "successUrl": ""
  "cancelUrl": ""

paymentMethods:
  -
    serviceName: "Checkout"
    methodId: "card"
    discordEmoji: ":credit_card:"
    name: ""
    description: ""
    minimalSum: 999.00