//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiryPayNew.Discord.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AiryPayNew.Discord.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🇬🇧.
        /// </summary>
        internal static string _languageEmoji {
            get {
                return ResourceManager.GetString("_languageEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string _languageName {
            get {
                return ResourceManager.GetString("_languageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balance.
        /// </summary>
        internal static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blocked.
        /// </summary>
        internal static string blocked {
            get {
                return ResourceManager.GetString("blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot&apos;s role ({0}) is lower than the product&apos;s role ({1}).\nFix this in role settings..
        /// </summary>
        internal static string botRoleTooLow {
            get {
                return ResourceManager.GetString("botRoleTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buyer.
        /// </summary>
        internal static string buyer {
            get {
                return ResourceManager.GetString("buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canceled.
        /// </summary>
        internal static string canceled {
            get {
                return ResourceManager.GetString("canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Number.
        /// </summary>
        internal static string cardNumber {
            get {
                return ResourceManager.GetString("cardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint details.
        /// </summary>
        internal static string complaintDetails {
            get {
                return ResourceManager.GetString("complaintDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a complaint.
        /// </summary>
        internal static string complaintModalTitle {
            get {
                return ResourceManager.GetString("complaintModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string complaintReason {
            get {
                return ResourceManager.GetString("complaintReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your complaint was registered..
        /// </summary>
        internal static string complaintRegistered {
            get {
                return ResourceManager.GetString("complaintRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for contacting us, your complaint has been sent and will be reviewed soon..
        /// </summary>
        internal static string complaintWasSent {
            get {
                return ResourceManager.GetString("complaintWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        ///   Looks up a localized string similar to Date.
        /// </summary>

        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date: `{0} (UTC)`.
        /// </summary>
        internal static string dateUtc {
            get {
                return ResourceManager.GetString("dateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        internal static string guildId {
            get {
                return ResourceManager.GetString("guildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shop information.
        /// </summary>
        internal static string infoCommandDescription {
            get {
                return ResourceManager.GetString("infoCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In process.
        /// </summary>
        internal static string inProcess {
            get {
                return ResourceManager.GetString("inProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use valid emoji.
        /// </summary>
        internal static string invalidEmoji {
            get {
                return ResourceManager.GetString("invalidEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing here yet Create a new product using the /product create command..
        /// </summary>
        internal static string noProducts {
            get {
                return ResourceManager.GetString("noProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing here yet. Users haven&apos;t made any purchases yet..
        /// </summary>
        internal static string noPurchases {
            get {
                return ResourceManager.GetString("noPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing here yet. Create a withdrawal using the /withdrawal command..
        /// </summary>
        internal static string noWithdrawals {
            get {
                return ResourceManager.GetString("noWithdrawals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paid.
        /// </summary>
        internal static string paid {
            get {
                return ResourceManager.GetString("paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New product has been created..
        /// </summary>
        internal static string productCreated {
            get {
                return ResourceManager.GetString("productCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product has been deleted..
        /// </summary>
        internal static string productDeleted {
            get {
                return ResourceManager.GetString("productDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product has been updated..
        /// </summary>
        internal static string productEdited {
            get {
                return ResourceManager.GetString("productEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price: **{0} ₽**.
        /// </summary>
        internal static string productPrice {
            get {
                return ResourceManager.GetString("productPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role: &lt;@&amp;{0}&gt;.
        /// </summary>
        internal static string productRole {
            get {
                return ResourceManager.GetString("productRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Products.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profit.
        /// </summary>
        internal static string profit {
            get {
                return ResourceManager.GetString("profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent Purchases.
        /// </summary>
        internal static string purchases {
            get {
                return ResourceManager.GetString("purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string settings_newLanguageSelected {
            get {
                return ResourceManager.GetString("settings.newLanguageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string settingsButton {
            get {
                return ResourceManager.GetString("settingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current store settings.
        /// </summary>
        internal static string settingsCurrent {
            get {
                return ResourceManager.GetString("settingsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change store language.
        /// </summary>
        internal static string settingsLanguageDescription {
            get {
                return ResourceManager.GetString("settingsLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language was successfully changed.
        /// </summary>
        internal static string settingsNewLanguageSelected {
            get {
                return ResourceManager.GetString("settingsNewLanguageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на :no_entry_sign: The selected payment method is invalid..
        ///   Looks up a localized string similar to Store without procucts can&apos;t be created. Create products using `/product create`..
        /// </summary>
        internal static string setup_createProductsFirst {
            get {
                return ResourceManager.GetString("setup.createProductsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :no_entry_sign: The selected payment method is invalid..
        /// </summary>
        internal static string setup_invalidPaymentMethod {
            get {
                return ResourceManager.GetString("setup.invalidPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на :no_entry_sign: The selected product is invalid..
        /// </summary>
        internal static string setup_invalidProduct {
            get {
                return ResourceManager.GetString("setup.invalidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay | {0} ₽.
        /// </summary>
        internal static string setup_paymentButton_label {
            get {
                return ResourceManager.GetString("setup.paymentButton.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay the [invoice]({0}) within 10 minutes..
        /// </summary>
        internal static string setup_paymentEmbed_description {
            get {
                return ResourceManager.GetString("setup.paymentEmbed.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AiryPay © {0}.
        /// </summary>
        internal static string setup_paymentEmbed_footer {
            get {
                return ResourceManager.GetString("setup.paymentEmbed.footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 💸 Payment.
        /// </summary>
        internal static string setup_paymentEmbed_title {
            get {
                return ResourceManager.GetString("setup.paymentEmbed.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на :no_entry_sign: Failed to create payment: {0}.
        /// </summary>
        internal static string setup_paymentError {
            get {
                return ResourceManager.GetString("setup.paymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 💳 Select a payment method.
        /// </summary>
        internal static string setup_selectPayment_placeholder {
            get {
                return ResourceManager.GetString("setup.selectPayment.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🛍️ Select a product to buy.
        /// </summary>
        internal static string setup_selectProduct_placeholder {
            get {
                return ResourceManager.GetString("setup.selectProduct.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на :warning: After updating shop products, this message must be deleted and reset using the /setup command..
        /// </summary>
        internal static string setup_selectProduct_warning {
            get {
                return ResourceManager.GetString("setup.selectProduct.warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shop ID.
        /// </summary>
        internal static string shopId {
            get {
                return ResourceManager.GetString("shopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shop Information.
        /// </summary>
        internal static string shopInformation {
            get {
                return ResourceManager.GetString("shopInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}.
        /// </summary>
        internal static string shopInfoTitle {
            get {
                return ResourceManager.GetString("shopInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shop not found.
        /// </summary>
        internal static string shopNotFound {
            get {
                return ResourceManager.GetString("shopNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string statusField {
            get {
                return ResourceManager.GetString("statusField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support.
        /// </summary>
        internal static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Terms of Service.
        /// </summary>
        internal static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Terms of Service.
        /// </summary>
        internal static string termsOfService {
            get {
                return ResourceManager.GetString("termsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на :no_entry_sign: Invalid card number specified..
        /// </summary>
        internal static string withdrawal_cardInvalid {
            get {
                return ResourceManager.GetString("withdrawal.cardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на :no_entry_sign: {0}.
        /// </summary>
        internal static string withdrawal_create_error {
            get {
                return ResourceManager.GetString("withdrawal.create.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 💵 Amount.
        /// </summary>
        internal static string withdrawal_created_amountField {
            get {
                return ResourceManager.GetString("withdrawal.created.amountField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 💳 Card Number.
        /// </summary>
        internal static string withdrawal_created_cardField {
            get {
                return ResourceManager.GetString("withdrawal.created.cardField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the funds do not arrive at the specified account within 24 hours, please contact support..
        /// </summary>
        internal static string withdrawal_created_description {
            get {
                return ResourceManager.GetString("withdrawal.created.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AiryPay © {0}.
        /// </summary>
        internal static string withdrawal_created_footer {
            get {
                return ResourceManager.GetString("withdrawal.created.footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 💸 Withdrawal Created.
        /// </summary>
        internal static string withdrawal_created_title {
            get {
                return ResourceManager.GetString("withdrawal.created.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -# In case of an error during withdrawal, the funds will be returned to the shop balance..
        /// </summary>
        internal static string withdrawal_created_warning {
            get {
                return ResourceManager.GetString("withdrawal.created.warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account number: ||{0}||.
        /// </summary>
        internal static string withdrawalAccountNumber {
            get {
                return ResourceManager.GetString("withdrawalAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount: **{0} ₽**.
        /// </summary>
        internal static string withdrawalAmount {
            get {
                return ResourceManager.GetString("withdrawalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:dd/MM/yyyy H:mm} Card.
        /// </summary>
        internal static string withdrawalDateCard {
            get {
                return ResourceManager.GetString("withdrawalDateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Withdrawals.
        /// </summary>
        internal static string withdrawals {
            get {
                return ResourceManager.GetString("withdrawals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status: **{0}**.
        /// </summary>
        internal static string withdrawalStatus {
            get {
                return ResourceManager.GetString("withdrawalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canceled.
        /// </summary>
        internal static string withdrawalStatus_canceled {
            get {
                return ResourceManager.GetString("withdrawalStatus_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In process.
        /// </summary>
        internal static string withdrawalStatus_inprocess {
            get {
                return ResourceManager.GetString("withdrawalStatus_inprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paid.
        /// </summary>
        internal static string withdrawalStatus_paid {
            get {
                return ResourceManager.GetString("withdrawalStatus_paid", resourceCulture);
            }
        }
    }
}
