# Positive decimal numbers 
defaultShopCommission: 12.0

ruKassaSettings:
  merchantId: 1
  token: "token goes here"
  userEmail: "user@gmail.com"
  userPassword: "123456"

finPaySettings:
  shopId: 1
  key1: "key1"
  key2: "key2"

payPalSettings:
  "clientId": 1
  "secret": "123456"
  "sandbox": true

stripeSettings:
  "apiKey": "key1"
  "successUrl": ""
  "cancelUrl": ""

paymentMethods:
  -
    serviceName: "Checkout"
    methodId: "card"
    discordEmoji: ":credit_card:"
    name: "Card"
    description: "Visa/Mastercard"
    minimalSum: 999.00