//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template (Localization.tt).
//     Changes to this file will be lost when the template is re-run.
//     To add or remove entries, edit Localization.resx then re-run the template.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiryPay.Discord.Localization;

using System.Globalization;
using System.Resources;

public class Localization
{
    protected static readonly ResourceManager _resourceManager =
        new("AiryPay.Discord.Localization.Localization", typeof(Localization).Assembly);

    protected readonly CultureInfo _culture;

    internal Localization(CultureInfo culture)
    {
        _culture = culture;
    }

    internal string LanguageName =>
        _resourceManager.GetString("_languageName", _culture)!;

    internal string LanguageEmoji =>
        _resourceManager.GetString("_languageEmoji", _culture)!;

    internal string ShopNotFound =>
        _resourceManager.GetString("shopNotFound", _culture)!;

    internal string ShopInformation =>
        _resourceManager.GetString("shopInformation", _culture)!;

    internal string Balance =>
        _resourceManager.GetString("balance", _culture)!;

    internal string Status =>
        _resourceManager.GetString("status", _culture)!;

    internal string Products =>
        _resourceManager.GetString("products", _culture)!;

    internal string ShopId =>
        _resourceManager.GetString("shopId", _culture)!;

    internal string Blocked =>
        _resourceManager.GetString("blocked", _culture)!;

    internal string Active =>
        _resourceManager.GetString("active", _culture)!;

    internal string NoProducts =>
        _resourceManager.GetString("noProducts", _culture)!;

    internal string Withdrawals =>
        _resourceManager.GetString("withdrawals", _culture)!;

    internal string NoWithdrawals =>
        _resourceManager.GetString("noWithdrawals", _culture)!;

    internal string InProcess =>
        _resourceManager.GetString("inProcess", _culture)!;

    internal string Paid =>
        _resourceManager.GetString("paid", _culture)!;

    internal string Canceled =>
        _resourceManager.GetString("canceled", _culture)!;

    internal string CardNumber =>
        _resourceManager.GetString("cardNumber", _culture)!;

    internal string Amount =>
        _resourceManager.GetString("amount", _culture)!;

    internal string StatusField =>
        _resourceManager.GetString("statusField", _culture)!;

    internal string Purchases =>
        _resourceManager.GetString("purchases", _culture)!;

    internal string NoPurchases =>
        _resourceManager.GetString("noPurchases", _culture)!;

    internal string Buyer =>
        _resourceManager.GetString("buyer", _culture)!;

    internal string Role =>
        _resourceManager.GetString("role", _culture)!;

    internal string Profit =>
        _resourceManager.GetString("profit", _culture)!;

    internal string Date =>
        _resourceManager.GetString("date", _culture)!;

    internal string Support =>
        _resourceManager.GetString("support", _culture)!;

    internal string Terms =>
        _resourceManager.GetString("terms", _culture)!;

    internal string WithdrawalStatusPaid =>
        _resourceManager.GetString("withdrawalStatus_paid", _culture)!;

    internal string WithdrawalStatusInprocess =>
        _resourceManager.GetString("withdrawalStatus_inprocess", _culture)!;

    internal string WithdrawalStatusCanceled =>
        _resourceManager.GetString("withdrawalStatus_canceled", _culture)!;

    internal string WithdrawalStatus =>
        _resourceManager.GetString("withdrawalStatus", _culture)!;

    internal string WithdrawalDateCard =>
        _resourceManager.GetString("withdrawalDateCard", _culture)!;

    internal string WithdrawalAmount =>
        _resourceManager.GetString("withdrawalAmount", _culture)!;

    internal string WithdrawalAccountNumber =>
        _resourceManager.GetString("withdrawalAccountNumber", _culture)!;

    internal string ShopInfoTitle =>
        _resourceManager.GetString("shopInfoTitle", _culture)!;

    internal string ProductPrice =>
        _resourceManager.GetString("productPrice", _culture)!;

    internal string ProductRole =>
        _resourceManager.GetString("productRole", _culture)!;

    internal string InfoCommandDescription =>
        _resourceManager.GetString("infoCommandDescription", _culture)!;

    internal string GuildId =>
        _resourceManager.GetString("guildId", _culture)!;

    internal string DateUtc =>
        _resourceManager.GetString("dateUtc", _culture)!;

    internal string TermsOfService =>
        _resourceManager.GetString("termsOfService", _culture)!;

    internal string Language =>
        _resourceManager.GetString("language", _culture)!;

    internal string InvalidEmoji =>
        _resourceManager.GetString("invalidEmoji", _culture)!;

    internal string ProductCreated =>
        _resourceManager.GetString("productCreated", _culture)!;

    internal string ProductEdited =>
        _resourceManager.GetString("productEdited", _culture)!;

    internal string ProductDeleted =>
        _resourceManager.GetString("productDeleted", _culture)!;

    internal string BotRoleTooLow =>
        _resourceManager.GetString("botRoleTooLow", _culture)!;

    internal string Setup_SelectProduct_Placeholder =>
        _resourceManager.GetString("setup.selectProduct.placeholder", _culture)!;

    internal string Setup_SelectProduct_Warning =>
        _resourceManager.GetString("setup.selectProduct.warning", _culture)!;

    internal string Setup_InvalidProduct =>
        _resourceManager.GetString("setup.invalidProduct", _culture)!;

    internal string Setup_SelectPayment_Placeholder =>
        _resourceManager.GetString("setup.selectPayment.placeholder", _culture)!;

    internal string Setup_InvalidPaymentMethod =>
        _resourceManager.GetString("setup.invalidPaymentMethod", _culture)!;

    internal string Setup_PaymentError =>
        _resourceManager.GetString("setup.paymentError", _culture)!;

    internal string Setup_PaymentEmbed_Title =>
        _resourceManager.GetString("setup.paymentEmbed.title", _culture)!;

    internal string Setup_PaymentEmbed_Description =>
        _resourceManager.GetString("setup.paymentEmbed.description", _culture)!;

    internal string Setup_PaymentEmbed_Footer =>
        _resourceManager.GetString("setup.paymentEmbed.footer", _culture)!;

    internal string Setup_PaymentButton_Label =>
        _resourceManager.GetString("setup.paymentButton.label", _culture)!;

    internal string Withdrawal_CardInvalid =>
        _resourceManager.GetString("withdrawal.cardInvalid", _culture)!;

    internal string Withdrawal_Create_Error =>
        _resourceManager.GetString("withdrawal.create.error", _culture)!;

    internal string Withdrawal_Created_Title =>
        _resourceManager.GetString("withdrawal.created.title", _culture)!;

    internal string Withdrawal_Created_Description =>
        _resourceManager.GetString("withdrawal.created.description", _culture)!;

    internal string Withdrawal_Created_AmountField =>
        _resourceManager.GetString("withdrawal.created.amountField", _culture)!;

    internal string Withdrawal_Created_CardField =>
        _resourceManager.GetString("withdrawal.created.cardField", _culture)!;

    internal string Withdrawal_Created_Footer =>
        _resourceManager.GetString("withdrawal.created.footer", _culture)!;

    internal string Withdrawal_Created_Warning =>
        _resourceManager.GetString("withdrawal.created.warning", _culture)!;

    internal string Settings =>
        _resourceManager.GetString("settings", _culture)!;

    internal string SettingsButton =>
        _resourceManager.GetString("settingsButton", _culture)!;

    internal string SettingsCurrent =>
        _resourceManager.GetString("settingsCurrent", _culture)!;

    internal string SettingsLanguageDescription =>
        _resourceManager.GetString("settingsLanguageDescription", _culture)!;

    internal string Settings_NewLanguageSelected =>
        _resourceManager.GetString("settings.newLanguageSelected", _culture)!;

    internal string SettingsNewLanguageSelected =>
        _resourceManager.GetString("settingsNewLanguageSelected", _culture)!;

    internal string Setup_CreateProductsFirst =>
        _resourceManager.GetString("setup.createProductsFirst", _culture)!;

    internal string ComplaintRegistered =>
        _resourceManager.GetString("complaintRegistered", _culture)!;

    internal string ComplaintModalTitle =>
        _resourceManager.GetString("complaintModalTitle", _culture)!;

    internal string ComplaintReason =>
        _resourceManager.GetString("complaintReason", _culture)!;

    internal string ComplaintDetails =>
        _resourceManager.GetString("complaintDetails", _culture)!;

    internal string ComplaintWasSent =>
        _resourceManager.GetString("complaintWasSent", _culture)!;

    internal string LanguageNotValid =>
        _resourceManager.GetString("languageNotValid", _culture)!;

    internal string ValidationFailed =>
        _resourceManager.GetString("validationFailed", _culture)!;

    internal string ShopIsBlocked =>
        _resourceManager.GetString("shopIsBlocked", _culture)!;

    internal string ProductNotFound =>
        _resourceManager.GetString("productNotFound", _culture)!;

    internal string InvalidShopId =>
        _resourceManager.GetString("invalidShopId", _culture)!;

    internal string TooManyProductsCreated =>
        _resourceManager.GetString("tooManyProductsCreated", _culture)!;

    internal string PaymentServiceNotFound =>
        _resourceManager.GetString("paymentServiceNotFound", _culture)!;

    internal string AccessDenied =>
        _resourceManager.GetString("accessDenied", _culture)!;

    internal string FailedToCreate =>
        _resourceManager.GetString("failedToCreate", _culture)!;

    internal string NoReasonAndDetails =>
        _resourceManager.GetString("noReasonAndDetails", _culture)!;

    internal string TooManyComplaints =>
        _resourceManager.GetString("tooManyComplaints", _culture)!;

    internal string InvalidWithdrawalAmount =>
        _resourceManager.GetString("invalidWithdrawalAmount", _culture)!;

    internal string InvalidWithdrawalDetails =>
        _resourceManager.GetString("invalidWithdrawalDetails", _culture)!;

    internal string InvalidWithdrawalMethod =>
        _resourceManager.GetString("invalidWithdrawalMethod", _culture)!;

    internal string WithdrawalAmountTooLow =>
        _resourceManager.GetString("withdrawalAmountTooLow", _culture)!;

    internal string InsufficientFunds =>
        _resourceManager.GetString("insufficientFunds", _culture)!;

    internal string Complaint =>
        _resourceManager.GetString("complaint", _culture)!;

}
