// <auto-generated />
using System;
using AiryPayNew.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiryPayNew.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240703155037_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Bills.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bill_secret");

                    b.Property<int>("BillStatus")
                        .HasColumnType("integer");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopId");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Purchases.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ShopId");

                    b.ToTable("purchases", (string)null);
                });

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Shops.Shop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Withdrawals.Withdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("Way")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WithdrawalStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("withdrawals", (string)null);
                });

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Bills.Bill", b =>
                {
                    b.HasOne("AiryPayNew.Domain.Entities.Products.Product", "Product")
                        .WithMany("Bills")
                        .HasForeignKey("ProductId");

                    b.HasOne("AiryPayNew.Domain.Entities.Shops.Shop", "Shop")
                        .WithMany("Bills")
                        .HasForeignKey("ShopId");

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("AiryPayNew.Domain.Entities.Shops.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Purchases.Purchase", b =>
                {
                    b.HasOne("AiryPayNew.Domain.Entities.Bills.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId");

                    b.HasOne("AiryPayNew.Domain.Entities.Shops.Shop", "Shop")
                        .WithMany("Purchases")
                        .HasForeignKey("ShopId");

                    b.Navigation("Bill");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Withdrawals.Withdrawal", b =>
                {
                    b.HasOne("AiryPayNew.Domain.Entities.Shops.Shop", "Shop")
                        .WithMany("Withdrawals")
                        .HasForeignKey("ShopId");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("AiryPayNew.Domain.Entities.Shops.Shop", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Products");

                    b.Navigation("Purchases");

                    b.Navigation("Withdrawals");
                });
#pragma warning restore 612, 618
        }
    }
}
