name: Deploy to Production

on:
  push:
    branches:
      - 'production'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(echo "${GITHUB_SHA}" | cut -c1-12)
          docker build --no-cache -t airypaynew:${IMAGE_TAG} -f src/AiryPayNew.Presentation/Dockerfile .
          docker tag airypaynew:${IMAGE_TAG} ${{ secrets.DOCKER_USERNAME }}/airypaynew:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/airypaynew:${IMAGE_TAG}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            IMAGE_TAG=$(echo "${GITHUB_SHA}" | cut -c1-12)
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/airypaynew:${IMAGE_TAG}
            docker image prune -f
            
            cd ./airy-pay-new
            docker compose down
            docker compose rm -f
            docker compose up -d --build