name: Deploy to Production

on:
  push:
    branches:
      - 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build projects
        run: dotnet build --no-restore

      - name: Run tests
        run: |
          dotnet test ./tests/AiryPay.Tests.Application/AiryPay.Tests.Application.csproj
          dotnet test ./tests/AiryPay.Tests.Architecture/AiryPay.Tests.Architecture.csproj

      - name: Deploy to Server
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            git config --global user.name "${{ github.actor }}"
            git config --global credential.helper 'store'
            echo "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git" > ~/.git-credentials

            cd ./airy-pay-new

            git pull origin production

            docker compose down
            docker compose up -d --build