name: Deploy to Production

on:
  push:
    branches:
      - 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            git config --global user.name "${{ github.actor }}"
            git config --global credential.helper 'store'
            echo "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git" > ~/.git-credentials

            cd ./airy-pay-new

            git pull origin production

            docker compose down

            docker compose up -d --build